services:
  - type: web
    name: realestate-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO
        value: mongodb+srv://username:password@cluster.mongodb.net/?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: qwert
    autoDeploy: true
    plan: free
    region: oregon

  - type: web
    name: realestate-client
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_FIREBASE_API_KEY
        value: AIzaSyAh68ux4nFMjHFJdhdJXQrWEv2QCzjPPjw
    autoDeploy: true
    plan: free
    region: oregon
