services:
  - type: web
    name: realestate-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO
        value: mongodb+srv://sayyidmarvanvt:sayyidmarvanvt@real-estate.iyt5p2i.mongodb.net/?retryWrites=true&w=majority&appName=real-estate
      - key: JWT_SECRET
        value: qwert
    autoDeploy: true
    plan: free
    region: oregon
    build:
      path: ./server
